### ISSUE TITLE
Results depend on transform of point cloud

### ISSUE THREAD

**Issue by ThoMut** [robotology/superquadric-lib#30] opened 2019-05-03 11:12 UTC
I run `Superquadric-Pipeline-Single` twice. 
First on a point cloud segment in camera frame.
Second time on the same segment but transformed to a frame where z axis aligns with principle axis of the segment

I get two very different results.
Is this expected?

first:
`Superquadric estimated:  [ 0.0339534, 0.150799, 0.0359551, 0.670291, 0.449664, 0.516203, -0.309417, 0.14, 2.50685, 1.59297, 1.59253]`

second:
`Superquadric estimated:  [ 0.0355826, 0.0719951, 0.0997269, 0.1117, 0.680769, 0.298284, -0.100897, 0.677961, 1.54269, 0.778541, 1.35143]`

left: second, right: fist
![results](https://user-images.githubusercontent.com/25347246/57133886-939b3f80-6da4-11e9-897a-e47c54a2b8bb.png)

**Comment by giuliavezzani** [comment] 2019-05-05 14:50
Hi @ThoMut, 

could you please send me the two point clouds? I'll try to reproduce this behavior in order to properly answer to your question!

**Comment by ThoMut** [comment] 2019-05-06 10:10
@giuliavezzani 
Thanks for the fast reply. Here are the two clouds:
[clouds.zip](https://github.com/robotology/superquadric-lib/files/3147466/clouds.zip)

**Comment by giuliavezzani** [comment] 2019-05-22 15:33
Hi @ThoMut, sorry for the late reply!

I found the reason of this undesired behavior. There was a bug in the computation of the initial superquadric starting from the point cloud.
I should have fixed it :smiley: 
Running the executable `Superquadric-PIpeline-Single`:
```
 Superquadric-Pipeline-Single /path/to/left
```
```
 Superquadric-Pipeline-Single /path/to/right
```

I obtain superquadrics with the same shape:

![results](https://user-images.githubusercontent.com/9597070/58187541-3e719000-7cb7-11e9-8dda-12405828b0e3.png)

Here are the values of the estimated superquadrics:

**Left**: 
```
[0.0151214, 0.0340539, 0.127362, 0.48192, 1.16588, 0.497439, -0.299483, 0.147063, 1.44361, 0.0563685, 1.26952]
```

**Right**:
```
 [0.0151214, 0.0340539, 0.127362, 0.48192, 1.16588, 0.497439, -0.299483, 0.147063, 1.44361, 0.0563685, 1.26952]
```
Let me know if this fixes your issue.

**Comment by giuliavezzani** [comment] 2019-06-18 07:40
@ThoMut I think I can close this.

**Closed as completed by giuliavezzani** 2019-06-18 07:40 UTC
